# Generated by Django 5.2 on 2025-05-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Тури'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.PositiveIntegerField(verbose_name='Кількість учасників'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(max_length=50, verbose_name='Складність'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='guide_name',
            field=models.CharField(max_length=100, verbose_name='Гід'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Відмінено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тур'),
        ),
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва точки')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Довгота')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Точка маршруту',
                'verbose_name_plural': 'Маршрутні точки',
                'ordering': ['order'],
            },
        ),
    ]
